/**
 * Layout Configuration Manager
 * 
 * Load and save layout configurations from/to config.ini
 */

import fs from 'fs';
import path from 'path';
import type { LayoutConfig, ProcessConfig } from './types.js';
import { LAYOUT_IDS } from './windows-api.js';

export type { LayoutConfig, ProcessConfig };

const DEFAULT_CONFIG_FILE = 'data/layout-manager-config.ini';

/**
 * Parse INI file to LayoutConfig
 */
export function parseIni(content: string): LayoutConfig {
  const config: LayoutConfig = {};
  const lines = content.split('\n');
  let currentSection: string | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith(';') || trimmed.startsWith('#')) {
      continue;
    }

    // Section header [ProcessName.exe]
    const sectionMatch = trimmed.match(/^\[(.+)\]$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1];
      config[currentSection] = {
        language: 'English',
        layoutId: LAYOUT_IDS.English,
      };
      continue;
    }

    // Key=Value pair
    if (currentSection) {
      const [key, value] = trimmed.split('=').map(s => s.trim());
      if (key === 'Language') {
        config[currentSection].language = value as 'English' | 'Russian';
      } else if (key === 'LayoutID') {
        // Parse hex string (0x4090409) or decimal
        const layoutId = value.startsWith('0x') 
          ? parseInt(value, 16) 
          : parseInt(value, 10);
        config[currentSection].layoutId = layoutId;
      }
    }
  }

  return config;
}

/**
 * Convert LayoutConfig to INI format
 */
export function toIni(config: LayoutConfig): string {
  let content = '; Layout Manager Configuration\n';
  content += '; Auto-generated by ELITE-DANGEROUS-NEXT\n\n';

  for (const [processName, procConfig] of Object.entries(config)) {
    content += `[${processName}]\n`;
    content += `Language=${procConfig.language}\n`;
    content += `LayoutID=0x${procConfig.layoutId.toString(16).toUpperCase()}\n\n`;
  }

  return content;
}

/**
 * Load configuration from file
 */
export function loadConfig(configFile: string = DEFAULT_CONFIG_FILE): LayoutConfig {
  const absolutePath = path.resolve(configFile);
  
  if (!fs.existsSync(absolutePath)) {
    return {};
  }

  try {
    const content = fs.readFileSync(absolutePath, 'utf-8');
    return parseIni(content);
  } catch (error) {
    console.error('Failed to load layout config:', error);
    return {};
  }
}

/**
 * Save configuration to file
 */
export function saveConfig(config: LayoutConfig, configFile: string = DEFAULT_CONFIG_FILE): void {
  const absolutePath = path.resolve(configFile);
  
  // Ensure directory exists
  const dir = path.dirname(absolutePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  try {
    const content = toIni(config);
    fs.writeFileSync(absolutePath, content, 'utf-8');
  } catch (error) {
    console.error('Failed to save layout config:', error);
    throw error;
  }
}

/**
 * Validate process name (must end with .exe)
 */
export function isValidProcessName(name: string): boolean {
  return name.toLowerCase().endsWith('.exe');
}

/**
 * Get language from layout ID
 */
export function getLanguageFromLayoutId(layoutId: number): 'English' | 'Russian' {
  if (layoutId === LAYOUT_IDS.Russian) {
    return 'Russian';
  }
  return 'English';
}
